export const categoryIconLabelMap: Record<string, string> = {
    'foodanddrink': 'Food & Drink',
    'groceries': 'Groceries',
    'salary': 'Salary',
    'bills': 'Bills',
    'rent': 'Rent',
    'travel': 'Travel',
    'transportation': 'Transportation',
    'shopping': 'Shopping',
    'education': 'Education',
    'family': 'Family',
    'entertainment': 'Entertainment',
    'health': 'Health',
    'other': 'Other',
};